server:
  port: 8081
spring:
  application:
    name: TaskFlow


  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 30s

  data:
    mongodb:
      uri: mongodb://user:1234@localhost:27017/mongok

    redis:
      host: localhost
      port: 6379
      timeout: 6000
    cache:
      type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234
    virtual-host: /

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.value.default.type: org.example.taskflow.DTO.messages.LogEntryMessage

exchanges:
  direct: taskFlow.direct.exchange
  fanout: taskFlow.fanout.exchange
  topic: taskFlow.topic.exchange
  DLX: dead.letter.exchange

queues:
  DLQ: dead.letter

routing-keys:
  dl-routing-key: dead.letter



